### ISSUE TITLE
When will all the code be released?

### ISSUE THREAD

**Issue by Taeyoung96** [haleqiu/AirDOS#1]
Thanks for your great work!  
BTW, there is nothing except `Readme.md` on this repository.  
Is there a specific date when all codes will be released?

**Comment by haleqiu** [comment]
Will release by May. Reorganizing the code now.

**Comment by haleqiu** [comment]
Thank you for checking out

**Comment by Taeyoung96** [comment]
@haleqiu  
I got it. Thanks for your reply. 👍

**Comment by haleqiu** [comment]
> 

sorry for being late on the reorganizing. Will release the data first. If you want to access the beta version, feel free to contact me through email.

**Comment by Taeyoung96** [comment]
@haleqiu  
Thanks for your reply.  
The code is not urgently needed, so I will check it when it is committed to GitHub.  :)
