### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Cai-RS** [haleqiu/AirDOS#10]
Thanks for your work! I have a question:  what does this code mean (in the GrabImageStereoHuman() in Tracking .cc)?
Eigen::MatrixXd eTrackId; eTrackId.resize(0,1);
Can the parameter of function resize() in Eigen be 0? Should it be eTrackId.resize(1,1)?

**Comment by learningintheworld** [comment]
> Thanks for your work! I have a question: what does this code mean (in the GrabImageStereoHuman() in Tracking .cc)? Eigen::MatrixXd eTrackId; eTrackId.resize(0,1); Can the parameter of function resize() in Eigen be 0? Should it be eTrackId.resize(1,1)?

Question response: The code eTrackId. resize (0,1) for this location; The purpose of creating an empty matrix is to avoid unnecessary memory allocation and element initialization, without any special restrictions. Even if this code is commented out, it can still run normally
