### ISSUE TITLE
How to run Tartanair shibuya dataset  on orbslam2

### ISSUE THREAD

**Issue by cjaijc** [haleqiu/AirDOS#12]
Airdos is impressing! I read your paper recently,and succsessfully build it. In your papers, i noticed that you runned Tartanair shibuya dataset on orbslam2 then computed the ATE. I really want to know how to run Tartanair shibuya dataset on orbslam2 to compare it with Airdos.
Thanks!

**Comment by haleqiu** [comment]
Hi @cjaijc, to ensure fair comparison, we modify the orbslam2 by masking the dynamic objects. You may replicate that results using the code in this repo. Change the config file by setting Human.OK to 0.

If you want to test the performance of the original orbslam2, you need to check the original orbslam repo. It may lost tracking due to the moving objects in the shibuya dataset.

**Comment by cjaijc** [comment]
thanks！i‘ll test it in the way you mentioned. wish you good luck!



---- Replied Message ----
| From | Yuheng ***@***.***> |
| Date | 03/21/2024 13:26 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [haleqiu/AirDOS] How to run Tartanair shibuya dataset on orbslam2 (Issue #12) |

Hi @cjaijc, to ensure fair comparison, we modify the orbslam2 by masking the dynamic objects. You may replicate that results using the code in this repo. Change the config file by setting Human.OK to 0.

If you want to test the performance of the original orbslam2, you need to check the original orbslam repo. It may lost tracking due to the moving objects in the shibuya dataset.

**Comment by cjaijc** [comment]
> Hi @cjaijc, to ensure fair comparison, we modify the orbslam2 by masking the dynamic objects. You may replicate that results using the code in this repo. Change the config file by setting Human.OK to 0.
> 
> If you want to test the performance of the original orbslam2, you need to check the original orbslam repo. It may lost tracking due to the moving objects in the shibuya dataset.

Hi！ Today by setting Human.OK to 0 , I changed the mask in Airdos and get reasonable outputs. But I still dont understand if it has any relation to the orbslam that you compared with. Does  Human.OK just decide whether there are masks in Airdos and haveno relation to orbslam？（Please forgive my ignorance, I am  a beginner in this field.
）

**Comment by cjaijc** [comment]
And I also want to know when running Airdos on kitti datasets to compare with orbslam , which yaml file should i use?Kittix.yaml or tartanair.yaml? Thanks!

**Comment by haleqiu** [comment]
@cjaijc you need to use the KITTI yaml file, because the camera intrinsic is different. For the config file problem, I am not quite understand, maybe I need more details.

**Comment by cjaijc** [comment]
> @cjaijc you need to use the KITTI yaml file, because the camera intrinsic is different. For the config file problem, I am not quite understand, maybe I need more details.
Thanks for your reply!  There were some issues with my previous statements, and now I generally understand some details in your paper.
