### ISSUE TITLE
Incorrect image link in the paper

### ISSUE THREAD

**Issue by GRF-Sunomikp31** [haleqiu/AirDOS#3]
Hi，Yuheng，thanks for the good work proposed，and I noticed that IV. SYSTEM OVERVIEW in the paper gave a wrong picture index at the beginning；At the same time, I also hope to see the code released as soon as possible, hhh.

**Comment by haleqiu** [comment]
@GRF-Sunomikp31 Thank you for pointing out, I really appreciate that. 
I will let you know when I update the paper and the code.
The dataset has been uploaded. If you're interested, you may take a look.

**Comment by GRF-Sunomikp31** [comment]
@haleqiu  Thank you reply， I will go and look at the dataset

**Comment by haleqiu** [comment]
@GRF-Sunomikp31 
Thank you for your patience. I have uploaded the code. If you encounter any issues, please let me know by leaving a comment.
