### ISSUE TITLE
When the example script was run, it was killed

### ISSUE THREAD

**Issue by sien110** [haleqiu/AirDOS#9]
When I run the following code:
./Examples/Stereo/stereo_human \
  ./Vocabulary/ORBvoc.txt \
  ./Examples/Stereo/config/tartanair.yaml \
  /.../TartanAir_shibuya/RoadCrossing07 \
  ./Evaluation/data/trajectory_output.txt

The following situation occurs:
the system is running offline without multi-threading!!!!!!!!!!!!!!!
Input sensor was set to: Stereo

Loading ORB Vocabulary. This could take a while...

Killed

**Comment by haleqiu** [comment]
@sien110 
Hi could you try to use `gdb` to check where the program failed?

**Comment by sien110** [comment]
I have checked the log files, and it seems that the program was interrupted due to a memory issue. How much memory does this program need to run smoothly?

**Comment by sien110** [comment]
@haleqiu This was my mistake, the error occurred due to the omission of ORBvoc.txt during compilation.

**Comment by haleqiu** [comment]
@sien110 I am glad to hear that you have solved this problem. I will close this issue.
Just out of curiosity, did you forget to add the ORBvoc.txt argument?
Any parts of the doc that is unclear to you?
